<?xml version='1.0' encoding='UTF-8'?><wsdl:definitions name="Service2ImplService" targetNamespace="http://deux.service.afcepf.fr" xmlns:ns1="http://schemas.xmlsoap.org/soap/http" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://deux.service.afcepf.fr" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <wsdl:types>
<xs:schema elementFormDefault="unqualified" targetNamespace="http://deux.service.afcepf.fr" version="1.0" xmlns:tns="http://deux.service.afcepf.fr" xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="methodeServiceDeux" type="tns:methodeServiceDeux"/>
<xs:element name="methodeServiceDeuxResponse" type="tns:methodeServiceDeuxResponse"/>
<xs:complexType name="methodeServiceDeux">
    <xs:sequence/>
  </xs:complexType>
<xs:complexType name="methodeServiceDeuxResponse">
    <xs:sequence>
      <xs:element minOccurs="0" name="reponseServiceDeux" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>
  </wsdl:types>
  <wsdl:message name="methodeServiceDeuxResponse">
    <wsdl:part element="tns:methodeServiceDeuxResponse" name="parameters">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="methodeServiceDeux">
    <wsdl:part element="tns:methodeServiceDeux" name="parameters">
    </wsdl:part>
  </wsdl:message>
  <wsdl:portType name="IService2">
    <wsdl:operation name="methodeServiceDeux">
      <wsdl:input message="tns:methodeServiceDeux" name="methodeServiceDeux">
    </wsdl:input>
      <wsdl:output message="tns:methodeServiceDeuxResponse" name="methodeServiceDeuxResponse">
    </wsdl:output>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="Service2ImplServiceSoapBinding" type="tns:IService2">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="methodeServiceDeux">
      <soap:operation soapAction="" style="document"/>
      <wsdl:input name="methodeServiceDeux">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="methodeServiceDeuxResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="Service2ImplService">
    <wsdl:port binding="tns:Service2ImplServiceSoapBinding" name="Service2ImplPort">
      <soap:address location="http://localhost:58080/BPEL-Seb/Service2Impl"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>